---
- name: update all servers
  hosts: microservers
  become: yes

  tasks:
  - name: update package lists
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: upgrade packages
    apt:
      name: "*"
      state: latest